### ISSUE TITLE
can't play "Server timed out"

### ISSUE THREAD

**Issue by Lrv-dev** [Melchizedek6809/WolkenWelten#1]
every time i try to play it appears server timed out 
![image](https://user-images.githubusercontent.com/42279779/109431878-68f19080-79e7-11eb-8b95-30b97796a340.png)

https://user-images.githubusercontent.com/42279779/109432025-06e55b00-79e8-11eb-819b-f3e57c825a59.mp4

**Comment by Melchizedek6809** [comment]
Got a new Release out, hopefully, it fixed this Issue :)
https://wolkenwelten.net/releases/linux-x86_64/wolkenwelten-linux-x86_64-master-2021-02-28-625C76A.tar.xz

**Comment by Melchizedek6809** [comment]
Another new Release, should finally fix this problem :)
https://wolkenwelten.net/releases/linux-x86_64/wolkenwelten-linux-x86_64-master-2021-03-01-813402F.tar.xz
