### ISSUE TITLE
MacOS: I can't move my cursor outside the game window.

### ISSUE THREAD

**Issue by wildwestrom** [Melchizedek6809/WolkenWelten#2]
So I open the game. I press escape to view my cursor, and I go to click the green button to make the game go fullscreen. Now for some reason I cannot move the cursor outside the window. I have to close the game. Fortunately if I switch apps by using cmd+tab. I can use my mouse elsewhere, it's just a bit annoying.

**Comment by Melchizedek6809** [comment]
Hey there, thanks for opening that Issue!

The newest release should fix that (and another related issue):
https://wolkenwelten.net/releases/macos/wolkenwelten-macos-master-2021-03-28-CEA7EBBB.tgz

It would be really nice if you could try it out and see if it actually fixes it for you :)

Have a nice day,
Ben

**Comment by wildwestrom** [comment]
The new release totally fixes that! 👍
