### ISSUE TITLE
No instructions to build for i686 machines

### ISSUE THREAD

**Issue by longboarder241** [Melchizedek6809/WolkenWelten#3]
while building despite having all dependencies I still get this message;
make: *** No rule to make target 'common/src/asm/i686.o', needed by 'wolkenwelten'.  Stop.

**Comment by Melchizedek6809** [comment]
Thank you for testing/opening the issue!
With the newest commit the game should now build for architectures like i686 where I haven't gotten around to writing ASM routines yet.
